### ISSUE TITLE
RESOURCE_EXHAUSTED

### ISSUE THREAD

**Issue by DenisCarriere** [dfuse-io/example-firehose-eosio-nodejs#2]
when setting flag:

```javascript
include_filter_expr: 'action == "transfer"'
```

Blocks: 150000000 => 150000005

```bash
Block #150000000 (08f0d1801685add3407cce1d753716e2edcf771af5ea3499f5dd476bc8f9a522, irreversible) - 18 Transactions, 1721 Actions (0 System Actions)
Block #150000001 (08f0d181b6a25010842df92563e169c4d4b91817e4eda5baa9dcd243c99822bc, irreversible) - 20 Transactions, 3121 Actions (0 System Actions)
Block #150000002 (08f0d182c5d91f74bed4f0dbb0d82f7ee027332d13019efa5fcd9c50d59afef9, irreversible) - 23 Transactions, 4776 Actions (0 System Actions)
Block #150000003 (08f0d183c5772651c3b83e49f3bef16bc105f8bd65f1844b112237d07e858cb7, irreversible) - 15 Transactions, 2386 Actions (0 System Actions)
An error occurred Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (7508774 vs. 4194304)
    at Object.exports.createStatusError (/Users/denis/Github/example-firehose-eosio-nodejs/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/Users/denis/Github/example-firehose-eosio-nodejs/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/Users/denis/Github/example-firehose-eosio-nodejs/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/denis/Github/example-firehose-eosio-nodejs/node_modules/grpc/src/client_interceptors.js:1277:15)
    at InterceptingListener._callNext (/Users/denis/Github/example-firehose-eosio-nodejs/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/denis/Github/example-firehose-eosio-nodejs/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/denis/Github/example-firehose-eosio-nodejs/node_modules/grpc/src/client_interceptors.js:1033:24 {
  code: 8,
  metadata: Metadata {
    _internal_repr: { 'grpc-status': [Array], 'grpc-message': [Array] },
    flags: 0
  },
  details: 'Received message larger than max (7508774 vs. 4194304)'
}
```

**Comment by maoueh** [comment]
gRPC has some message size limitation that can be tweaked. I found https://stackoverflow.com/questions/56768254/getting-error-8-resource-exhausted-received-message-larger-than-max-15217288/56768255#56768255.

Please test and report.

**Comment by DenisCarriere** [comment]
Yes, this works! 👍  tested and can now stream those large blocks
